#!/bin/bash

source script/nginx.sh

set -o nounset
set -o errexit

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0;m"

DIR=$(pwd)
BUILDDIR=$DIR/build
NGINX_DIR=nginx

setup_local_directories () {
    if [ ! -d $BUILDDIR ]; then
        mkdir $BUILDDIR > /dev/null 2>&1
        mkdir $BUILDDIR/$NGINX_DIR > /dev/null 2>&1
    fi

    if [ ! -d "vendor" ]; then
        mkdir vendor > /dev/null 2>&1
    fi
}

clean () {
    rm -rf build vendor
}

if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "clean" ]]; then
	clean
    else
	echo "clean is the only option"
    fi
else
    setup_local_directories
    install_nginx
fi
