#!/bin/bash

which lcov 1>/dev/null 2>&1
if [ $? != 0 ]
then
    echo "You need to have lcov installed in order to generate the test coverage report"
    exit 1
fi

echo "Building"
export AR_FLAGS=cr
./autogen.sh > /dev/null 2>&1
./configure > /dev/null 2>&1
make clean > /dev/null 2>&1
make > /dev/null 2>&1
make check > /dev/null 2>&1

echo "Generating Coverage Report"
lcov --base-directory src --directory src -c -o librepsheet_test.info
lcov --remove librepsheet_test.info "/usr*" -o librepsheet_test.info
lcov --remove librepsheet_test.info "src/mpc.*" -o librepsheet_test.info
rm -rf coverage
genhtml -o coverage -t "librepsheet test coverage" --num-spaces 4 librepsheet_test.info
