#!/bin/bash

which lcov 1>/dev/null 2>&1
if [ $? != 0 ]
then
    echo "You need to have lcov installed in order to generate the test coverage report"
    exit 1
fi

./autogen.sh
./configure
make clean
make
make check

lcov --base-directory src --directory src -c -o librepsheet_test.info
lcov --remove librepsheet_test.info "/usr*" -o librepsheet_test.info
lcov --remove librepsheet_test.info "src/mpc.*" -o librepsheet_test.info
rm -rf test_coverage
genhtml -o test_coverage -t "librepsheet test coverage" --num-spaces 4 librepsheet_test.info

chromium-browser test_coverage/index.html
